image: node:14

stages:
  - test
  - deploy

before_script:
  - npm install

cache:
  paths:
    - node_modules/

test:
  stage: test
  script:
    - npm run lint

pages:
  stage: deploy
  script:
    - npm install expo-cli json -g
    - json -I -f package.json -e 'this.homepage="https://aicacia.gitlab.io/expo-mathcafe/"'
    - npm run build.web
    - mv web-build public
  artifacts:
    paths:
      - public
